name: JavaScript Testing
on:
  pull_request:
    paths:
      - 'webpack/**'
      - 'package.json'
      - '.github/workflows/js_tests.yml'

jobs:
  test_js:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout plugin
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Copy configuration files
        run: |
          cp config/package-lock.json.plugin package-lock.json
      - name: Install plugin npm dependencies
        run: npm ci
      - name: Run plugin linter
        run: |
          npm run lint
          npm run lint:spelling
      - name: Run plugin tests
        run: npm run test
      - name: Publish Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
