name: Ruby tests
on:
  push:
    branches: [master, foreman_2_3, foreman_2_5]
  pull_request:
    branches: [master, foreman_2_3, foreman_2_5]

defaults:
  run:
    working-directory: /projects/foreman

jobs:
  test_ruby:
    defaults:
      run:
        working-directory: /projects/foreman
    env:
      PGHOST: postgres
      PGUSER: foreman
      PGPASS: foreman
      RAILS_ENV: test
      host: postgres
      WORKDIR: /projects/foreman
      BUNDLE_PATH: vendor/bundle
      GIT_COMMITTER_NAME: "gh_actions"
      GIT_COMMITTER_EMAIL: "gh_actions@rh_cloud.foreman"

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/theforeman/tfm_plugin_test:foreman_2_3
        #      volumes:
        #- ${{ github.workspace }}/projects/foreman_rh_cloud:/projects/foreman_rh_cloud

    services:
      postgres:
        image: quay.io/jomitsch/postgres-with-evr
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: foreman
          POSTGRES_PASSWORD: foreman

    steps:
      - name: Checkout foreman_rh_cloud repo
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/projects/foreman_rh_cloud
      - name: Fix git config
        run: |
          cp -Rf $GITHUB_WORKSPACE/projects/foreman_rh_cloud /projects/
          cd /projects/foreman
          /usr/bin/entrypoint.sh git config --global user.name $GIT_COMMITTER_NAME
          /usr/bin/entrypoint.sh git config --global user.email $GIT_COMMITTER_EMAIL
      - name: Run tests suite
        run: |
          cd /projects/foreman
          /usr/bin/entrypoint.sh /usr/bin/run_tests.sh
