name: Ruby tests
on:
  push:
    branches: [foreman_3_9]
  pull_request:
    branches: [foreman_3_9]


concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rubocop:
    name: Rubocop
    uses: theforeman/actions/.github/workflows/rubocop.yml@v0
    with:
      command: bundle exec rubocop --parallel --format github

  test:
    name: Ruby
    needs: rubocop
    strategy:
      fail-fast: false
      matrix:
        foreman:
          - 3.9-stable
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_rh_cloud
      postgresql_container: ghcr.io/theforeman/postgresql-evr
      test_existing_database: false
      foreman_version: ${{ matrix.foreman }}
